### ISSUE TITLE
[torchx/local_scheduler] Remove dependency to pr_set_deathsig for handling orphans/zombies

### ISSUE THREAD

**Issue by kiukchung** [pytorch/torchx#104]
## Description
Currently local_scheuduler (https://github.com/pytorch/torchx/blob/master/torchx/schedulers/local_scheduler.py#L317-L319) depends on the linux pr_set_deathsig to ensure that when the scheduler is terminated so are the processes that were launched with the scheduler. Unfortunately pr_set_deathsig is only available on linux based platforms and not on macos. 

## Motivation/Background
Support running torchx examples and basic functionalities on macos. 

## Detailed Proposal
The same issue exists in pytorch (torch.distributed.elastic.multiprocessing). See this PR (https://github.com/pytorch/pytorch/pull/61602). The solution for local_scheduler is the same.

## Alternatives
N/A - the alternative is to drop support for macos altogether and have macos users use the torchx docker image to test things out. While we recommend users to use linux based systems for using torchx in production, it is plausible for someone new to torchx to test things out on their laptop hence we'd like to make the "quickstart" path work on macos.

## Additional context/links
N/A

**Comment by d4l3k** [comment]
@aivanou is this still an issue after https://github.com/pytorch/torchx/commit/c14dae7e3d21d4af07e2496c6c6e798012ced2da#diff-09539702926f7f10882b16e1d08bb03975dd490bb5ead62cf6d9e84dde0dbf16 ?

**Comment by aivanou** [comment]
#141 resolves the issue
