### ISSUE TITLE
Add Torchx Validate command

### ISSUE THREAD

**Issue by aivanou** [pytorch/torchx#132]
## Description
Torchx allows users to develop their own components. Torchx component is defined as a python function with several restrictions as described in https://pytorch.org/torchx/latest/quickstart.html#defining-your-own-component

The `torchx validate` cmd will help users to develop the components.

`torchx validate ~/my_component.py:func` whether the component is a valid component or not. If component is not valid, the command will print the detailed message explaining what is wrong with the function.

**Comment by d4l3k** [comment]
I think this overlaps with https://github.com/pytorch/torchx/issues/129 . If we add validation/error printing to run you can just use --dry_run as validation

**Comment by kiukchung** [comment]
closing since we now validate on-the-fly so no need for a `torchx validate` subcommand, just `torchx run` (or dryrun) -> look at the error message (if any) -> iterate.
