### ISSUE TITLE
[RFC] A collect_env.py script to automatically get system diagnostics

### ISSUE THREAD

**Issue by kiukchung** [pytorch/torchx#154]
## Description
A script to get and print diagnostic information for users who are filing TorchX bug reports.

## Motivation/Background
PyTorch has a script that users can use to copy paste system diagnostics info to append to the bug report issues that they file with pytorch. We should have something similar for TorchX.

```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
```

## Detailed Proposal
Write a `collect_env.py` for TorchX that outputs (list non-exhaustive) relevant info that will help us accurately debug user issues:

1. torchx version
2. kfp, slurm (scheduler) version
3.  docker version
4. platform
5. which CSP (aws, gcp, azure or on-prem) - we might not be able to collect this automatically, instead this might just be a user input

NOTE: we can actually expand on this idea and write a "diagnostics job" that users can launch that returns information about cluster setup (e.g. that the network settings are correctly configured by trying to connect to nodes in the distributed job).

## Alternatives
Instead of a script, have the user fill out a template manually (not optimal since its inconvenient and cumbersome and also leads to human errors (typos etc))

## Additional context/links
see pytorch's bug report template: https://github.com/pytorch/pytorch/issues/new?assignees=&labels=&template=bug-report.md

**Comment by d4l3k** [comment]
closed by https://github.com/pytorch/torchx/commit/e6017daf54a97c556239105b7d4151e1db0f6976
