### ISSUE TITLE
[torchx][api] Deprecate Torchx Session Name

### ISSUE THREAD

**Issue by aivanou** [pytorch/torchx#227]
Torchx Runner has a concept of `session_name`. When user creates a Runner, he/she may provide `session_name`. If no argument provided, the `session_name` will be set to: `torchx_$user` . 

This parameter is then used to create a full job name as: `session_name-$app_der.name` . 

The problem is that the default session name `torchx_$user` is not bound by the max length, and in theory can be very long. This may affect user jobs without them understanding the root cause. 

In order to solve this, we can make default session name as `torchx_` instead, and omit `$user` part.

**Comment by kurman** [comment]
`torchx run --scheduler local_cwd --scheduler_args log_dir=/tmp utils.echo --msg "Hello $USER"` yields:

...
**local_cwd://torchx/echo-mvnppz5dsrkzmc**
torchx 2022-05-12 12:51:55 INFO     Waiting for the app to finish...
torchx 2022-05-12 12:51:55 INFO     Job finished: SUCCEEDED

I believe it was closed in https://github.com/pytorch/torchx/pull/215
