### ISSUE TITLE
[torchx/docker] update base image to pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime

### ISSUE THREAD

**Issue by kiukchung** [pytorch/torchx#299]
## Description
Update base image in https://github.com/pytorch/torchx/blob/main/torchx/runtime/container/Dockerfile#L1 from 
`pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime` to `pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime`.

## Motivation/Background
We currently use the 1.9.0 base image because we've been running our CI with the assumption of cuda10.2 (we don't explicitly require cuda 10.2, we've always built the docker this way hence its an "assumption" not a requirement)

## Detailed Proposal
See description

## Alternatives
N/A

## Additional context/links
N/A

**Comment by d4l3k** [comment]
closed by https://github.com/pytorch/torchx/commit/bbecc7cc321c57448afe52e20ebaafff9260f296
