### ISSUE TITLE
[torchx/specs] Add a metadata map to specs.Role

### ISSUE THREAD

**Issue by kiukchung** [pytorch/torchx#301]
## Description
Add a metadata (Dict[str, str]) parameter to specs.Role

## Motivation/Background
Currently, any properties of the AppDef that is scheduler specific (and hence not exposed in the parameters of AppDef or Role) need to either be exposed as a scheduler runopt or users have to use the `dryrun()` api to manipulate the scheduler request prior to submission. 

This is suboptimal as:
1. there are properties intrinsic to the AppDef/Role(e.g. oncall handle) which are being exposed as scheduler runopts as a workaround
2. there is no good way to specify different values for different roles via runopts. Typically runopts are applied on the whole job not to a specific Role.
3. dryrun + manual field injection is not a great UX and exposes too much of the scheduler details making the launch process tightly coupled to the scheduler

## Detailed Proposal
Add a `metadata: Dict[str, str]` to `Role`. Each scheduler can read specific properties of the role (sub-gang) from this metadata. Hence an application that has multiple Roles and wants to set different oncall handles per role can do:

```
AppDef(
  name="multi-role",
  roles = [
      Role(
          name="trainer",
          metadata={"oncall": "trainer-team@fb.com"},
          # ...
      ), 
      Role(
          name="reader",
          metadat={"oncall": "data-team@fb.com"},
          # ....
      ),
   ],
)
```

## Alternatives
The two known workarounds have been developed as an alternative but have proven to be suboptimal for reasons explained above.

## Additional context/links
N/A

**Comment by aivanou** [comment]
https://github.com/pytorch/torchx/pull/308
