### ISSUE TITLE
separate .torchxconfig for fb/ and oss

### ISSUE THREAD

**Issue by colin2328** [pytorch/torchx#339]
## Description
We want to have a FB internal .torchxconfig file to specify scheduler_args for internal cluster and a OSS .torchxconfig file to run on public clusters

**Comment by aivanou** [comment]
@colin2328  can you pls check the wiki: https://www.internalfb.com/intern/wiki/PyTorch_R2P/TorchX/Project_Setup_(fbcode)/#managing-fb-and-oss-torc 

This is already available for usage
