### ISSUE TITLE
Advanced Pipeline Example Errors on KFP

### ISSUE THREAD

**Issue by sam-h-bean** [pytorch/torchx#340]
## Link
https://pytorch.org/torchx/main/examples_pipelines/kfp/advanced_pipeline.html#sphx-glr-examples-pipelines-kfp-advanced-pipeline-py

## What does it currently say?
The pipeline.yaml can be generated and run on Kubeflow

## What should it say?
Unknown, I believe it is a race condition in the code where the pipeline begins execution before the download of the data is complete.

## Why?
<img width="804" alt="Screen Shot 2021-11-13 at 1 36 46 AM" src="https://user-images.githubusercontent.com/43734688/141608949-e41c0d23-4131-4eb8-82c6-e86aeb579e8e.png">

**Comment by aivanou** [comment]
Hello! This happens because directory `/tmp/output` is not present on the container that you are launching. Try to change this to `/tmp/tiny-imagenet-200.zip` . Let me know whether it works !

**Comment by sam-h-bean** [comment]
@aivanou That did not work `FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tiny-imagenet-200.zip'`
