### ISSUE TITLE
[torchx/specs] Remove redundant SchedulerBackend in favor of str

### ISSUE THREAD

**Issue by kiukchung** [pytorch/torchx#342]
## Description + Motivation/Background
`SchedulerBackend` is simply an alias to `str` which was added to make things clear that the str passed into certain APIs should actually map to a scheduler. But it makes it more confusing (probably because SchedulerBackend looks like a "class" due to the camelcasing).

## Detailed Proposal
Remove SchedulerBackend alias https://github.com/pytorch/torchx/blob/main/torchx/specs/api.py#L34 and just use `str`

All occurences of `SchedulerBackend` should be replaced with `str`.

## Alternatives
N/A

**Comment by d4l3k** [comment]
Closed by https://github.com/pytorch/torchx/pull/436
