### ISSUE TITLE
Document usage of .torchxconfig

### ISSUE THREAD

**Issue by kiukchung** [pytorch/torchx#421]
## Link
Current `.torchxconfig` docs (https://pytorch.org/torchx/main/runner.config.html) explain how it works and its APIs but does not provide any practical guidance on what configs can be put into it and why its useful.

## What does it currently say?
Nothing wrong with what it currently says. 

## What should it say?
Should add more practical user guide on what are the supported configs in `.torchxconfig` and under what circumstances it gets picked up with the `torchx` CLI. As well as:

1. Examples
2. Best Practices

## Why?
Current .torchxconfig docs is useful to the programmer but not for the user.

**Comment by d4l3k** [comment]
Closed by https://github.com/pytorch/torchx/pull/434
