### ISSUE TITLE
Improve torchx/resources README

### ISSUE THREAD

**Issue by kiukchung** [pytorch/torchx#470]
## Link
https://github.com/pytorch/torchx/tree/main/resources

## What does it currently say?
```
**Creating EKS cluster**
eksctl create cluster -f torchx-dev-eks.yml

**Creating KFP**
kfctl apply -V -f torchx-dev-kfp.yml
```

## What should it say?
For the **Creating EKS Cluster** it should actually list out how to create `torchx-dev-eks.yml`. The instructions are in `torchx-dev-eks-template.yml`, so just pulling those out to the README would be good.

For **Creating KFP**, it is missing the steps to generate `torchx-dev-kfp.yml`. I'm assuming you do this by following the instructions on the aws eks kfp website (https://www.kubeflow.org/docs/distributions/aws/deploy/install-kubeflow/), but a quick look at those docs doesn't seem like its obvious.

## Why?
Following the README step by step doesn't work due to missing files.

**Comment by d4l3k** [comment]
closed by #505
