### ISSUE TITLE
[slurm scheduler] Add --wait and --kill-on-bad-exit cfgs

### ISSUE THREAD

**Issue by kiukchung** [pytorch/torchx#479]
## Description
Add the SRUN's `--wait` and `--kill-on-bad-exit` options to slurm scheduler's run options. 

Might be worth making `--kill-on-bad-exit=1` the default (at least for dist.ddp since it expects gang semantics) and have a sensible default value for `--wait` (60second seems reasonable)

## Motivation/Background
See: https://github.com/pytorch/pytorch/issues/76287#issuecomment-1118034508 

TL;DR it looks like on SLURM, if only a subset (`k/n` where `k << n`) tasks finish (successfully or unsuccessfully), SLURM will NOT finish the job. This can be problematic for edge-cases where the user script has a subset of the workers finish while the others are still working or are stuck. Since DDP assumes gang semantics, it is acceptable for the scheduler to terminate the entire job if a subset of the workers have finished and a specific timeout (specified by `--wait` has passed).

FWIW - torchelastic already handles this for worker failures but not for worker successes. That is, if `k/n` workers fail, torchelastic will globally kill (and optionally restart) the workers on remote nodes. Additionally if ALL the local_ranks succeed, torchelatic will enter an [exit barrier](https://github.com/pytorch/pytorch/blob/master/torch/distributed/elastic/agent/server/api.py#L863). However if a subset of the local_ranks finish successfully torchelastic will continue monitoring the other local ranks for success/failure. If the other ranks are stuck, then the job will be stuck indefinitely with nothing to time it out.

## Detailed Proposal
Add `--wait` and `--kill-on-bad-exit` runoptions here: https://github.com/pytorch/torchx/blob/main/torchx/schedulers/slurm_scheduler.py#L283

SLURM docs: 
1. https://slurm.schedmd.com/srun.html#OPT_kill-on-bad-exit
2. https://slurm.schedmd.com/srun.html#OPT_wait

Make `--kill-on-bad-exit=1` and `--wait=60` by default

## Alternatives
N/A

**Comment by ax3l** [comment]
@d4l3k @kiukchung could this also be supported as `#SBATCH --kill-on-bad-exit=0/1` ?
