### ISSUE TITLE
Support Ray 2.0

### ISSUE THREAD

**Issue by d4l3k** [pytorch/torchx#584]
## Description

Ray 2.0 made `get_address_and_port` no longer public + added a bunch of pyre changes. We need to find a replacement for get_address_and_port, fix the types and then upgrade to Ray 2.0.

 https://github.com/ray-project/ray/blob/1d2735093d7f883b637c978ebb4593a56dffafbf/python/ray/train/_internal/utils.py#L62

## Additional context/links

* failing test https://github.com/pytorch/torchx/runs/7979175375?check_suite_focus=true

**Comment by ljjsalt** [comment]
#587
