### ISSUE TITLE
pip install fails with ModuleNotFound on `importlib-metadata` when adding named_resources

### ISSUE THREAD

**Issue by kiukchung** [pytorch/torchx#644]
## 🐛 Bug

For some odd reason when the following conditions are met my project fails to install with `pip` when adding custom named resources in the entrypoint as suggested by https://pytorch.org/torchx/latest/advanced.html#registering-named-resources.

Issue seems to be that when invoking `pip install .` from a virtualenv, pip creates a subprocess in one of the build steps
which runs without the dependencies installed in the virtualenv. Hence when I add my custom named resources, the code (see full trace below) ends up  in `torchx/torchx/util/entrypoints.py` which requires `importlib_metadata`, which is installed on my virtualenv where I ran `pip install` from but not on the overlay-fs the `build_meta` steps seems to be running in a subprocess outside the virtualenv (explains why it can't find `importlib_metadata`).

For now I'm getting by with installing via `python setup.py develop`, but would be nice to understand why `pip install` fails when adding entrypoints to configure custom resources with torchx.

# `pyproject.toml` 

> same error happens if I just inline `entry_points` in `setup.py`

```
[project.entry-points."torchx.named_resources"]
g4d.xlarge = "mfive.aws.resources:g4d_xlarge"
g4d.2xlarge = "mfive.aws.resources:g4d_2xlarge"
g4d.4xlarge = "mfive.aws.resources:g4d_4xlarge"
g4d.8xlarge = "mfive.aws.resources:g4d_8xlarge"
g4d.16xlarge = "mfive.aws.resources:g4d_16xlarge"
```

# pip install .

> same error with `pip install -e .`
> NOTE: I'm using pyenv to create a virtual env

```
ubuntu@ip-10-2-87-95(main↑1|●1✚7…1)% pip install  -e .                            ~/workspace/mfive
Obtaining file:///home/ubuntu/workspace/mfive
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/home/ubuntu/.pyenv/versions/3.9.13/envs/venv39/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/ubuntu/.pyenv/versions/3.9.13/envs/venv39/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ubuntu/.pyenv/versions/3.9.13/envs/venv39/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-99xq4z23/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 446, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-99xq4z23/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-99xq4z23/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-99xq4z23/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 483, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-99xq4z23/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 10, in <module>
        File "/home/ubuntu/workspace/mfive/mfive/aws/resources.py", line 26, in <module>
          from torchx.specs import Resource
        File "/home/ubuntu/workspace/torchx/torchx/__init__.py", line 8, in <module>
          from .version import (  # noqa F401; noqa F401
        File "/home/ubuntu/workspace/torchx/torchx/version.py", line 8, in <module>
          from torchx.util.entrypoints import load
        File "/home/ubuntu/workspace/torchx/torchx/util/entrypoints.py", line 9, in <module>
          import importlib_metadata as metadata
      ModuleNotFoundError: No module named 'importlib_metadata'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Module (check all that applies):
 * [ ] `torchx.spec`
 * [ ] `torchx.component`
 * [ ] `torchx.apps`
 * [ ] `torchx.runtime`
 * [ ] `torchx.cli`
 * [ ] `torchx.schedulers`
 * [ ] `torchx.pipelines`
 * [ ] `torchx.aws`
 * [ ] `torchx.examples`
 * [x] `other`

## To Reproduce

1.
1.
1.

## Environment

 - torchx version (e.g. 0.1.0rc1):
 - Python version:
 - OS (e.g., Linux):
 - How you installed torchx (`conda`, `pip`, source, `docker`):
 - Docker image and tag (if using docker):
 - Git commit (if installed from source):
 - Execution environment (on-prem, AWS, GCP, Azure etc):
 - Any other relevant information:

**Comment by d4l3k** [comment]
`importlib-metadata` is one of the requirements for TorchX. Can you check that it was properly installed from the requirements.txt file?

https://github.com/pytorch/torchx/blob/main/requirements.txt

**Comment by d4l3k** [comment]
Sorry -- I see what the question is now. It's very strange that importlib_metadata is availablei n the python environment but not the pip install -e .... It's very strange that torchx is available but not importlib_metadata. If you explicitly depend on that in the mfive setup.py does it solve that issue? 

https://peps.python.org/pep-0517/#build-environment

> The get_requires_for_build_wheel and get_requires_for_build_sdist hooks are executed in an environment which contains the bootstrap requirements specified in the pyproject.toml file.

**Comment by kiukchung** [comment]
Thanks @d4l3k . So you could add build-system requirements in your `pyproject.toml`  as:

```
[build-system]
requires = [
    "setuptools",
    "importlib-metadata",
    "typing-inspect",
    "docstring-parser==0.8.1"
]
```

But the issue is that you need to port your `setup.py` to `pyproject.toml` (or at the least `setup.cfg`). Disabling PEP517 seems to do the trick for now.

```
pip install --no-use-pep517 -e .
```

**Comment by d4l3k** [comment]
@kiukchung when you say "you need to" are you saying that on your side or something that we can do under TorchX? I still don't quite understand why pip is running importing all of the entrypoints via some generated "setup.py"

**Comment by kiukchung** [comment]
> But the issue is that you need to port your setup.py to pyproject.toml (or at the least setup.cfg). 

By "you" here I mean the owner of the project that depends on torchx (in this case me == mfive)
