### ISSUE TITLE
[torchx.runner] Support Kubernetes

### ISSUE THREAD

**Issue by kiukchung** [pytorch/torchx#67]
## Description
Implement a k8s_scheduler for the `torchx.runner` to allow launching `torchx.AppDef`s as a standalone job on Kubernetes.

## Motivation/Background
Currently `torchx-0.1.0.dev` only has support for launching onto a "local" scheduler:

```
# only this is supported
torchx run --scheduler local ...
```
This is only useful for local validation and testing, we need a way to run components onto a real scheduler. 

**NOTE:** Running on Kubeflow Pipelines is supported for pipelines, we are specifically talking about launching as a **job** (not a workflow/pipeline).

## Detailed Proposal
Add k8s support so that this is possible:

```
# CLI
torchx run --scheduler k8s ...
```

## Alternatives
N/A

## Additional context/links
N/A

**Comment by d4l3k** [comment]
Initial support was landed via https://github.com/pytorch/torchx/commit/e1a28b8c609545c1db419e1f7e7ae2e88c31ec04

still need some more polish such as better dependency management + log fetching
