### ISSUE TITLE
[torchx.pipelines] Add an Airflow pipeline adapter

### ISSUE THREAD

**Issue by kiukchung** [pytorch/torchx#68]
## Description
Add support for airflow pipeline adapter for torchx AppDefs.

## Motivation/Background
torchx-0.1.0.dev only supports Kubeflow Pipelines

## Detailed Proposal
Essentially add: https://github.com/pytorch/torchx/tree/master/torchx/pipelines/kfp for airflow

## Alternatives
N/A

## Additional context/links
N/A

**Comment by d4l3k** [comment]
Example at https://pytorch.org/torchx/main/pipelines/airflow.html

If we think we need a full airflow component we can reopen this down the line
