### ISSUE TITLE
Docker workspace: How to specify "latest" (nightly) base image?

### ISSUE THREAD

**Issue by kiukchung** [pytorch/torchx#684]
## ❓ Questions and Help

For my docker workspace (e.g. scheduler == "local_docker" or "aws_batch"), I'd like to use a base image that is published on a nightly cadence. So I have this `Dockerfile.torchx`

```
# Dockerfile.torchx
ARGS IMAGE
ARGS WORKSPACE

FROM $IMAGE

WORKDIR /workspace/mfive
COPY $WORKSPACE .

# installs my workspace (has setup.py)
RUN pip install -e .[dev]
```

In my `.torchxconfig` I've specified the latest default image as:

```
# .torchxconfig

[dist.ddp]
image = registry.gitlab.aws.dev/mfive/mfive-nightly:latest
```

The nightly build tags the nightly image as `latest` in addition to the `YYYY.MM.DD` (e.g. `mfive-nightly:2023.01.15`) but because the [`DockerWorkspace`'s build argument has `pull=False`](https://github.com/pytorch/torchx/blob/main/torchx/workspace/docker_workspace.py#L126) this won't work since `latest` will be cached.

Is there a better way for me to specify a "use-the-latest" base image from the repo policy when building a docker workspace?

cc) @d4l3k

**Comment by kurman** [comment]
My take here is that `latest` is a specific behavior here and I think [pull=False](https://github.com/pytorch/torchx/blob/main/torchx/workspace/docker_workspace.py#L126) parameter is wrong here. However from release process, using a tagged image probably is a better approach and don't rely on the `latest` image in order to have deterministic builds.

**Comment by kiukchung** [comment]
How would I be able to specify the "most recent" tag? For instance, my nightly build produces the following base images:

1. mfive-nightly:2023.01.17
2. mfive-nightly:2023.01.16 
3. mfive-nightly:2023.01.15
4. .. and so on...

come 2023.01.18 there will be a `mfive-nightly:2023.01.18` so without having to specify this manually as:

```
$ torchx run dist.ddp --image mfive-nightly:2023.01.18 ...
```

**Comment by d4l3k** [comment]
@kiukchung we do an explicit pull() on the image, just before the build -- we do it separately so it can fail to pull and still run the build for local images. https://github.com/pytorch/torchx/blob/main/torchx/workspace/docker_workspace.py#L112

It looks like we don't actually set always pull in AWS batch https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html maybe we should do that

I don't think docker has a good way of doing "most recent" but if you want we could add in a new build argument for "date" and set it to the iso8601 date or something
