### ISSUE TITLE
[torchx.runner] Add support for SLURM

### ISSUE THREAD

**Issue by kiukchung** [pytorch/torchx#70]
## Description
Add support for a `slurm_scheduler` for torchx runner (not pipelines!)

## Motivation/Background
torchx-0.1.0.dev only supports running locally

## Detailed Proposal
Should be able to run a component as a standalone SLURM job as such:

```
# CLI
torchx run --scheduler slurm ...
```

## Alternatives
N/A

## Additional context/links
N/A

**Comment by d4l3k** [comment]
Initial support landed as part of https://github.com/pytorch/torchx/commit/ccfe332059f86fd2ca09f9f3ad5b41e8750a0441
