### ISSUE TITLE
Dryrun information not printed

### ISSUE THREAD

**Issue by Sara-KS** [pytorch/torchx#713]
## 🐛 Bug

When running `torchx run --dryrun`, the command line no longer prints out the logging information. 

Module (check all that applies):
 * [ ] `torchx.spec`
 * [ ] `torchx.component`
 * [ ] `torchx.apps`
 * [ ] `torchx.runtime`
 * [x ] `torchx.cli`
 * [ ] `torchx.schedulers`
 * [ ] `torchx.pipelines`
 * [ ] `torchx.aws`
 * [ ] `torchx.examples`
 * [ ] `other`

## To Reproduce
This can be reproduced with multiple schedulers. As an example, I am using the [Quickstart "Hello world"](https://pytorch.org/torchx/latest/quickstart.html)

1.Activate a python environment with the TorchX nightly commits included
2.(torch-nightly)$ torchx run --dryrun --scheduler local_cwd my_component.py:greet --user "
3. Results in nothing shown on the console via the logger

Steps to revert the behavior:
1.  set the environment variable `export LOGLEVEL=INFO`
2. (torch-nightly)$ torchx run --dryrun --scheduler local_cwd my_component.py:greet --user "
3. Prints expected output

## Expected behavior

=== APPLICATION === 
and
=== SCHEDULER REQUEST ===

information should be printed

## Environment

 - torchx version (e.g. 0.1.0rc1): torchx-0.5.0dev0
 - Python version: 3.10.5
 - OS (e.g., Linux): Mac terminal
 - How you installed torchx (`conda`, `pip`, source, `docker`): source
 - Docker image and tag (if using docker):
 - Git commit (if installed from source): 47976f7 and later
 - Execution environment (on-prem, AWS, GCP, Azure etc): tested locally and on Kubernetes
 - Any other relevant information:

## Additional Context
In `torchx/cli/main.py` the default logging behavior was changed from INFO to WARNING. If WARNING is now the recommended default, need to update docs for dryrun or change the logging type for dryrun information.

**Comment by kiukchung** [comment]
oops sorry about that I changed the default loglevel to WARNING on the CLI in https://github.com/pytorch/torchx/commit/47976f77df0f50128658ba947efadb88235c66d1 to reduce output spamming. 

Changed the dryrun info to use `print()` instead of `log.info()` in this PR: https://github.com/pytorch/torchx/pull/714

**Comment by kiukchung** [comment]
@starpit, @Sara-KS  have you found loglevel=INFO to be a better default log level than loglevel=WARNING?

**Comment by Sara-KS** [comment]
@kiukchung Thanks for resolving this! Regarding the log level default, I think `loglevel=WARNING` is the preferred default for production-level jobs and is the default that the `logging` python package uses.
