### ISSUE TITLE
[torchx.components] Add support for distributed AppDefs

### ISSUE THREAD

**Issue by kiukchung** [pytorch/torchx#72]
## Description
Add support for running AppDefs that specify `num_replicas > 1` and/or that have multiple `Role`s. 

## Motivation/Background
Currently distributed app defs are only supported on the local scheduler (each replica/role modeled as a UNIX process).

## Detailed Proposal
TODO add detailed proposal 

## Alternatives
N/A

## Additional context/links
N/A

**Comment by d4l3k** [comment]
This is now supported via the slurm and kubernetes schedulers.

**Comment by d4l3k** [comment]
KFP has distributed AppDef support now
