### ISSUE TITLE
Codecov pip install fails in TorchX GitHub actions

### ISSUE THREAD

**Issue by Sara-KS** [pytorch/torchx#726]
## 🐛 Bug

Installing Codecov via pip install is no longer a supported option as mentioned in the [Codecov blog post from April 12th.](https://about.codecov.io/blog/message-regarding-the-pypi-package/)  This change is currently causing the python unit test GitHub action to fail. The recommended solution from Codecov is to migrate to using the Codecov Github Action. 

Module (check all that applies):
 * [ ] `torchx.spec`
 * [ ] `torchx.component`
 * [ ] `torchx.apps`
 * [ ] `torchx.runtime`
 * [ ] `torchx.cli`
 * [ ] `torchx.schedulers`
 * [ ] `torchx.pipelines`
 * [ ] `torchx.aws`
 * [ ] `torchx.examples`
 * [ x] `other`

## To Reproduce

1. Trigger running the TorchX Github action: .github/workflows/python-unittests.yaml 
2 . pip install coverage codecov line fails

Error message:
```
ERROR: Could not find a version that satisfies the requirement codecov (from versions: none)
ERROR: No matching distribution found for codecov
```

## Environment

 - torchx version (e.g. 0.1.0rc1):
 - Python version: All
 - OS (e.g., Linux):
 - How you installed torchx (`conda`, `pip`, source, `docker`):
 - Docker image and tag (if using docker):
 - Git commit (if installed from source):
 - Execution environment (on-prem, AWS, GCP, Azure etc):
 - Any other relevant information: GitHub Actions

**Comment by kiukchung** [comment]
Thanks for reporting! I've fixed this as part of my PR: https://github.com/pytorch/torchx/pull/727
