### ISSUE TITLE
In AWS Batch Scheduler, Support Rank 0 worker to be consistently on Batch job's main node. 

### ISSUE THREAD

**Issue by stoicio** [pytorch/torchx#730]
## Description

Currently, when launching distributed jobs in AWS Batch, the `Rank 0` worker can land on any arbitrary node. Instead enable `Rank 0` node to consistently land on Batch job's main node. (`AWS_BATCH_JOB_MAIN_NODE_INDEX

## Motivation/Background

This will improve observability of the distributed job by easily locating logs for the `rank0` worker. Without this support logs for each nodes in the batch job will have to be examined to locate the `rank0` worker logs

**Comment by kiukchung** [comment]
The ask is a new rdzv implementation for which worker rank 0 always runs on agent rank 0. Please create a feature request on https://github.com/pytorch/pytorch/issues.
