### ISSUE TITLE
With Volcano, why or when to use TorchX?

### ISSUE THREAD

**Issue by zxcware** [pytorch/torchx#735]
### Question

We can run Pytorch DDP or elastic with just Volcano, right? What does TorchX offer differently from Volcano?

**Comment by kiukchung** [comment]
TorchX uses Volcano for gang scheduling on kubernetes. And yes you can run with vanilla Volcano on k8s. I’d say using TorchX offers better portability and integration with PyTorch. 

For example, you if you wanted to launch on different schedulers (or if your organization had multiple schedulers) then you can launch the same job simply by changing the “-s <SCHEDULDER_NAME>”. 

As for better PyTorch integration, TorchX components (eg “ddp” and “spmd”) essentially templetize job definitions so it makes it easy for you to launch your job without having to fiddle with too many configs and env vars. One such example is running ddp in “debug” mode. With TorchX it would be as easy as adding a “—debug=True” flag which in turn sets environment variables such as “NCCL_LAUNCH_BLOCKING=1” to help debug your job.

**Comment by zxcware** [comment]
> TorchX uses Volcano for gang scheduling on kubernetes. And yes you can run with vanilla Volcano on k8s. I’d say using TorchX offers better portability and integration with PyTorch.
> 
> For example, you if you wanted to launch on different schedulers (or if your organization had multiple schedulers) then you can launch the same job simply by changing the “-s <SCHEDULDER_NAME>”.
> 
> As for better PyTorch integration, TorchX components (eg “ddp” and “spmd”) essentially templetize job definitions so it makes it easy for you to launch your job without having to fiddle with too many configs and env vars. One such example is running ddp in “debug” mode. With TorchX it would be as easy as adding a “—debug=True” flag which in turn sets environment variables such as “NCCL_LAUNCH_BLOCKING=1” to help debug your job.

I see. It has better usability for PyTorch applications. Thanks.
