### ISSUE TITLE
Is this repository no longer maintained?

### ISSUE THREAD

**Issue by ccharest93** [pytorch/torchx#766]
### Please note that this issue tracker is not a help form and this issue will be closed.

Before submitting, please ensure you have gone through our
[documentation](https://pytorch.org/torchx).

### Question
Torch elastic redirects to this repository but it doesn't seem very active, is there a slack/ discord channel? I want to run DDP on kubernetes, is there another way i am not aware of? If torchx is best way, i'd like to contribute! Any pointers where i could start?

**Comment by kiukchung** [comment]
You can get started at the torchx docs page: https://pytorch.org/torchx/latest/. For k8s take a look at: https://pytorch.org/torchx/latest/schedulers/kubernetes.html

FWIW torchelastic (`torch.distributed.elastic` aka `torchrun`) and torchx serve to slightly different purposes. The former is a torch.distributed-aware process launcher (similar to what `mpirun` is to MPI). The later is a job launcher.

**Comment by kiukchung** [comment]
contributions are welcome! For k8s specific PRs you can cc) @kiukchung  and @d4l3k

**Comment by kiukchung** [comment]
Closing, feel free to reopen if you have further questions.

**Comment by d4l3k** [comment]
There is also the pytorch slack (and #torchx ) where we tend to have more involved discussions on things. Happy to invite you if you send me your email
