### ISSUE TITLE
Do not pin docstring-parser to a fixed version

### ISSUE THREAD

**Issue by moeslami** [pytorch/torchx#771]
## Description
We request to please do not pin the docstring-parser to a fixed version such as 0.8.1 as it caused conflicts with other python packages we consume along with torchx. Thanks.

## Motivation/Background
Pinning docstring-parser to a fixed version like docstring-parser==0.8.1 causes dependency conflicts when installing some other python packages.

## Detailed Proposal
Make torchx depend on docstring-parser>=0.8.1,<=0.15.0 or something similar

**Comment by kiukchung** [comment]
Thanks for the suggestion. https://github.com/pytorch/torchx/pull/772 should do it.
