### ISSUE TITLE
Docker build verbosity

### ISSUE THREAD

**Issue by ccharest93** [pytorch/torchx#813]
## Description
Changing the docker image build to its low level implementation so it can be more verbose.

## Motivation/Background
Building the docker image can take quite some time, and for new users this makes it seem like the program is stuck (especially since the default base image that includes torchx is so big). Making it more verbose is not only a quality of life improvement for all users of the docker workspace, it also gives better visibility into the build process, potentially allowing optimization on the dockerfile.

On a side note, what is the rational for naming Dockerfile.torchx instead of just using a normal Dockerfile, is there a difference in the format?

## Detailed Proposal
Replacing the current docker build API call with its low level implementation. This would require instantiating a low-level client and processing the build event stream to show in real time to docker build commands. Also a processing function for the stream to be printing to screen correctly.

## Additional context/links
https://github.com/pytorch/torchx/blob/19497eb1d2649f66cd12ca1eeed77353085f07e0/torchx/workspace/docker_workspace.py#L118

**Comment by d4l3k** [comment]
https://docker-py.readthedocs.io/en/stable/api.html#docker.api.build.BuildApiMixin.build

**Comment by ccharest93** [comment]
Yeah the PR is written #815 and in draft mode, just waiting on #819 to merge before removing it from draft mode.

**Comment by d4l3k** [comment]
Ah nice, just saw that

I recently ran into this issue and well
