### ISSUE TITLE
Missing quotes on torchx install command.

### ISSUE THREAD

**Issue by mdevino** [pytorch/torchx#849]
## 📚 Documentation

I was running the [TorchX Quickstart](https://pytorch.org/torchx/latest/quickstart.html) tutorial and I would get a message saying that the package couldn't be found.

![image](https://github.com/pytorch/pytorch/assets/19861348/04af51ca-945f-4bc0-ae9a-a098ade6ddf3)

After looking around, I realized the command would only work with quotes. I'll be opening a PR to add the quotes to the documentation.

## Link
[](https://pytorch.org/torchx/latest/quickstart.html)

## What does it currently say?
`pip install torchx[dev]`

## What should it say?
`pip install "torchx[dev]"`

## Why?
Because, otherwise, it says the package cannot be found.

**Comment by d4l3k** [comment]
Looks like this is a zsh only issue -- fish/bash work fine

**Comment by mdevino** [comment]
> Looks like this is a zsh only issue -- fish/bash work fine

Oh, I didn't even think it could shell-specific. Thanks for sharing!
