### ISSUE TITLE
Fix Nightly push permissions

### ISSUE THREAD

**Issue by ryxli** [pytorch/torchx#875]
### Please note that this issue tracker is not a help form and this issue will be closed.

Before submitting, please ensure you have gone through our
[documentation](https://pytorch.org/torchx).

### Question

Is it possible to fix the nightly push permissions? Many pr have been merged into main, but last nightly release was from 2024.2.12 (https://pypi.org/project/torchx-nightly/)

Currently nightly push is failing due to:

```
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/          
         The user 'd4l3k' isn't allowed to upload to project 'torchx-nightly'.  
         See https://pypi.org/help/#project-name for more information.          
```
(https://github.com/pytorch/torchx/actions/runs/8614806013/job/23608993087#step:6:473)

**Comment by d4l3k** [comment]
Taking a look -- likely caused by the token expiring, thanks for flagging!

**Comment by d4l3k** [comment]
I've updated the token -- rerunning now https://github.com/pytorch/torchx/actions/runs/8614806013

**Comment by d4l3k** [comment]
Oh the permission issue is on torchx-nightly not torchx :/ Chatting with folks to get that fixed

**Comment by d4l3k** [comment]
Lets try this again :) https://github.com/pytorch/torchx/actions/runs/8614806013

**Comment by d4l3k** [comment]
New nightly just went live -- https://pypi.org/project/torchx-nightly/2024.4.10/

@ryxli thanks for flagging this!
